config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/profskipulag/ST540102:
      branch: main
      repo: https://github.com/profskipulag/ST540102
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/profskipulag/ST540102 git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-maroon-indri.sh
        container: qc.acc_seedy-sepia-ostrich
  QC.Doc:
    repos:
      github.com/profskipulag/ST540102 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-orange-chimpanzee.sh
        container: qc.doc_nerdy-celadon-elephant
      github.com/profskipulag/ST540102 git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-carmine-toucan.sh
        container: qc.doc_fuzzy-ruby-tang
      github.com/profskipulag/ST540102 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-celadon-chipmunk.sh
        container: qc.doc_surly-russet-wolf
  QC.Lic:
    repos:
      github.com/profskipulag/ST540102 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-copper-cuttlefish.sh
        container: qc.lic_smelly-ecru-kakapo
  QC.Sec:
    repos:
      github.com/profskipulag/ST540102 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-pumpkin-saola.sh
        container: qc.sec_thirsty-teal-setter
  QC.Sty:
    repos:
      github.com/profskipulag/ST540102 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-turquoise-hamster.sh
        container: qc.sty_skinny-corn-anteater
  QC.Uni:
    repos:
      github.com/profskipulag/ST540102 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-white-cat.sh
        container: qc.uni_breezy-bronze-grouse
  QC.Ver:
    repos:
      github.com/profskipulag/ST540102 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-azure-rat.sh
        container: qc.ver_smelly-viridian-nightingale
timeout: 5400
